name: CI/CD Spring Boot Microservice

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tkg31/spring-boot-crud-app
      VERSION: ${{ github.ref_name == 'main' && 'v1.0.0' || github.ref_name }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:$VERSION .
        docker push $IMAGE_NAME:$VERSION

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Set Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

    - name: Fetch K8s YAMLs from main branch
      run: |
        git fetch origin main
        git checkout origin/main -- k8s/${VERSION%%.*}

    - name: Deploy to EKS
      run: |
        kubectl apply -f k8s/${VERSION%%.*}/deployment.yaml
        kubectl apply -f k8s/${VERSION%%.*}/service.yaml
        kubectl apply -f k8s/${VERSION%%.*}/ingress.yaml
