name: CI/CD Spring Boot Microservice

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: tkg31/spring-boot-crud-app
      VERSION: ${{ github.ref_name == 'main' && 'v1.0.0' || github.ref_name }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t $IMAGE_NAME:$VERSION .
        docker push $IMAGE_NAME:$VERSION

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > ~/.kube/config

    - name: Fetch k8s YAMLs from main
      run: |
        git fetch origin main
        git checkout origin/main -- k8s/${VERSION%%.*}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/${VERSION%%.*}/deployment.yaml
        kubectl apply -f k8s/${VERSION%%.*}/service.yaml
        kubectl apply -f k8s/${VERSION%%.*}/ingressroute.yaml
        kubectl apply -f k8s/${VERSION%%.*}/middleware.yaml
